// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu0eLz-x9ltT7qU08ma7mpqnwa9rfYs-k',
    appId: '1:725776442176:web:03fec027362211661a50a5',
    messagingSenderId: '725776442176',
    projectId: 'askchuck',
    authDomain: 'askchuck.firebaseapp.com',
    storageBucket: 'askchuck.appspot.com',
    measurementId: 'G-6P32Q9VEVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLZ5Lq0V0PJFb-_vu1j_Ydn36-8nOmO2U',
    appId: '1:725776442176:android:4e1ec53ef1ded5c51a50a5',
    messagingSenderId: '725776442176',
    projectId: 'askchuck',
    storageBucket: 'askchuck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuW90IOI-uc3wX2FKygd8uOsF-rw2deoI',
    appId: '1:725776442176:ios:c7fafc7b780fe5cc1a50a5',
    messagingSenderId: '725776442176',
    projectId: 'askchuck',
    storageBucket: 'askchuck.appspot.com',
    iosClientId: '725776442176-psra36a1b253j29s3mejncfdfc7qhjsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.askChuck',
  );
}
